### ISSUE TITLE
pre-proposal: add `extraSchemas` to notebook format

### ISSUE THREAD

**Issue by agoose77** [jupyter/enhancement-proposals#96]
## Background
During the Jupyter Notebook workshop, we established three JEP drafts that would prepare the notebook format for additional cell types, and address the problem of un-typed metadata. On the latter issue, current notebook users have no way to indicate to the notebook consumer that metadata should conform to a particular schema. This prevents the validation of the metadata by third parties, and precludes the ability for frontends to display rich-editing interfaces for this metadata[^1]

## Proposal
A separate JEP will move to deprecate the `nbformat` and `nbformat_minor` top-level properties, in favour of a direct `$schema` property. This must contain a URI to an nbformat schema.

This JEP will extend the previous schema to include an `extraSchemas` property. This optional property may contain an array of URIs that refer to additional schemas. These schemas may not conflict with one another, and all `extraSchemas` must validate the document alongside the root `$schema` in order for a notebook to be considered valid. To begin with, any schema in `extraSchemas` must conform with a restrictive metaschema that permits the addition of properties _only_ to the notebook and cell metadata. In future, this may be relaxed.

## Examples

Example of _valid_ notebook under this proposal:    
```json
{
    "$schema": "https://jupyter.org/schema/notebook/4.6/notebook-4.6.schema.json"
    "extraSchemas": [
        "my-extension-schema-uri"
    ],
    "metadata": { 
        "my-extension": { ... }    
    }
    "cells": [ ... ]
}
``` 

Example of schema referenced in `extraSchemas` (`"my-extension-schema-uri"`):
```json5
{
    "$schema": "https://jupyter.org/schema/notebook/4.6/notebook-4.6.schema.json"
    "metadata": { 
        "type": "object",
        "required": ["my-extension"]  # Adds new `my-extension` property to the notebook metadata
    }
}
``` 

[^1]: e.g. with tools like [react-jsonschema-form](https://rjsf-team.github.io/react-jsonschema-form/)

**Comment by agoose77** [comment]
@bollwyvl both good points. I think you're recorded as planning to attend the meeting in 10 minutes, so let's discuss it there, and report back the findings!

**Comment by willingc** [comment]
FYI @MSeal @rgbkrk

**Comment by tonyfast** [comment]
i spent a little time thinking about a few tools different kinds of extra schema we could define. these are just some use cases for reference or discussion later on. 

_the schema are written in toml for density. they get weird when we are deep in the schema._

## specific source patterns

constrain that a document can't be saved with out a blank cell. ideally, we'd want to have a nice `$comment` to inform the user.
    
```toml
"$description" = "require all cells are non-empty"
[properties.cells.items.properties.source.if]
type = "string"

[properties.cells.items.properties.source.then]
"$anchor" = "non-empty-string"
minLength = 1
pattern = "^\s*\S"

[properties.cells.items.properties.source.else]
type = "array"
minLength = 1
contains = {"%ref": "#non-empty-string"}
```

## notebook metadata extensions

as @agoose77  described above, we might want to extend the notebook level metadata. in this example, we image kernelspec extracted to its own schema

```toml
[properties.metadata]
required = ["kernelspec"]

[properties.metadata.properties.kernelspec]
"$ref" = "https://github.com/jupyter/nbformat/blob/main/nbformat/v4/nbformat.kernelspec.v4.5.schema.json"
```

## cell metadata extensions

we might want to constrain the cell metadata schema. currently, there are quite a few cell schema that might be useful to extract into more composable representations later on. in this example, slide types are constrained.

```toml
"$description" = "the cell metadata slide type schema"
[properties.cells.items.properties.metadata]
required = ["slide_type"]

[properties.cells.items.properties.metadata.properties.slide_type]
enum = ["slide", "sub-slide"]
```

## display data data extension for a json schema

we might want to constrain our new display data types. this example requires json schema mimetypes to abide json schema.

```toml
[properties.cells.items.properties.outputs.items.if]
output_type = "display_data"

[properties.cells.items.properties.outputs.items.then.properties.data."application/schema+json"]
"$ref" = "https://json-schema.org/draft/2020-12/schema"
```

## display data data metadata extension 

a vendor might want to constrain their output metadata. below we constrain `my_extension`s metadata.

```toml
[properties.cells.items.properties.outputs.items.if]
output_type = "display_data"

[properties.cells.items.properties.outputs.items.then.properties.metadata.properties.my_extension.properties]
foo = {type = "string"}
```
